#!/bin/bash

set -o vi

# Prohibit overriding existing files with bash redirection
# Use 'command |> file' if sure
#set -o noclobber

shopt -s checkwinsize

# Append to the history file, do not override it
shopt -s histappend

# don't put duplicate lines in the history and ignore lines starting from space
export HISTCONTROL=ignoreboth:erasedups
export HISTSIZE=10240
# save history timestamps
export HISTTIMEFORMAT='%F %T '

# After each command, save and reload history
#export PROMPT_COMMAND="history -a; history -c; history -r"

# Integration with ccache
if [ -d "/usr/lib/ccache" ]; then
    export PATH="/usr/lib/ccache:$PATH"
    export CCACHE_PATH="/usr/bin"
fi

[ -d "$HOME/local/bin" ] && export PATH="$HOME/local/bin:$PATH"
[ -d "$HOME/.bin" ]      && export PATH="$HOME/.bin/:$PATH"

export CDPATH=.:$HOME/Work
export PAGER='less'
export EDITOR='vim'
export VISUAL=$EDITOR

# press Ctrl-D twice to quit shell
export IGNOREEOF=1

if [ -f /etc/arch-release ]; then
    OS=arch
else
    # Guessing
    OS=debian
fi

