#! /bin/bash

# Colors for prompt {{{
bold=$(  tput bold   )
black=$( tput setaf 0)
red=$(   tput setaf 1)
green=$( tput setaf 2)
yellow=$(tput setaf 3)
blue=$(  tput setaf 4)
purple=$(tput setaf 5)
cyan=$(  tput setaf 6)
white=$( tput setaf 7)
reset=$( tput sgr0   )
# }}}

[ -r /usr/share/git/completion/git-prompt.sh ] && source /usr/share/git/completion/git-prompt.sh

__git_branch='$(__git_ps1 "%s")'
__git_stash_status='$(git stash list 2>/dev/null | wc -l | sed -e "/^0$/d" -e "s/^.\+$/\ +{\0}/")'
PS1="\[$green\][\[$yellow\]\A \[$green\]\w \[$purple\]($__git_branch$__git_stash_status)\[$green\]] \$\[$reset\] "
