#! /bin/bash

TMUX_FILE="/usr/share/doc/tmux/examples/bash_completion_tmux.sh"
load_file $TMUX_FILE

alias tmain='tmux new -A -s Main'
alias ttemp='tmux new -A -s Temp'
alias tlist='tmux list-sessions'
